/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClassView;

import ClassBeans.UsuariosBeans;
import java.awt.Color;
import java.awt.Container;
import javax.swing.JLabel;

/**
 *
 * @author devops
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        ViewLogin pi = new ViewLogin();
        UsuariosBeans user = new UsuariosBeans();
        initComponents();
        Container c = getContentPane();
         String usuario = System.getProperty("Usuario: ","");
         c.add(new JLabel(usuario));
        getContentPane().setBackground(Color.lightGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuNovaOs = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuOsAberta = new javax.swing.JMenuItem();
        menuOsFechada = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuProduto = new javax.swing.JMenuItem();
        menuNovosProdutos = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenuItem();

        setTitle("Tela Principal");

        menuNovaOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorio (3).png"))); // NOI18N
        menuNovaOs.setText("Centro de Serviços");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem4.setText("Nova OS");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuNovaOs.add(jMenuItem4);

        menuOsAberta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuOsAberta.setText("OS Abertas");
        menuOsAberta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOsAbertaActionPerformed(evt);
            }
        });
        menuNovaOs.add(menuOsAberta);

        menuOsFechada.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuOsFechada.setText("OS Fechadas");
        menuNovaOs.add(menuOsFechada);

        menuRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuRelatorio.setText("Relatórios");
        menuNovaOs.add(menuRelatorio);

        jMenuBar1.add(menuNovaOs);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/controle-de-estoque.png"))); // NOI18N
        jMenu2.setText("Estoque");

        menuProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuProduto.setText("Produtos");
        menuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(menuProduto);

        menuNovosProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        menuNovosProdutos.setText("novos produtos");
        menuNovosProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovosProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(menuNovosProdutos);

        menuConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        menuConsulta.setText("Consulta");
        jMenu2.add(menuConsulta);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(708, 405));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ViewNovaOS novaos = new ViewNovaOS();
        novaos.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuOsAbertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOsAbertaActionPerformed
        ViewOSAberta aberta = new ViewOSAberta();
        aberta.setVisible(true);
    }//GEN-LAST:event_menuOsAbertaActionPerformed

    private void menuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutoActionPerformed
       viewEstoque estoque = new viewEstoque();
       estoque.setVisible(true);
               
    }//GEN-LAST:event_menuProdutoActionPerformed

    private void menuNovosProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovosProdutosActionPerformed
        viewProdutos prod = new viewProdutos();
        prod.setVisible(true);
    }//GEN-LAST:event_menuNovosProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menuConsulta;
    private javax.swing.JMenu menuNovaOs;
    private javax.swing.JMenuItem menuNovosProdutos;
    private javax.swing.JMenuItem menuOsAberta;
    private javax.swing.JMenuItem menuOsFechada;
    private javax.swing.JMenuItem menuProduto;
    private javax.swing.JMenuItem menuRelatorio;
    // End of variables declaration//GEN-END:variables
}
